# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: github-token-limit
    main: ./cmd
    binary: github-token-limit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'main.Version={{.Version}}'
      - -X 'main.Commit={{.ShortCommit}}'
      - -X 'main.Date={{.Date}}'

release:
  github:
    owner: clivewalkden
    name: go-github-token-limit

archives:
  - id: github-token-limit
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - '^build'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: Dependency Updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other
      order: 9999

nfpms:
  - id: github-token-limit-deb
    package_name: github-token-limit
    vendor: Clive Walkden
    homepage: https://github.com/clivewalkden/go-github-token-limit
    maintainer: Clive Walkden <info@clivewalkden.com>
    description: This executable returns the number of requests remaining for the GitHub API. If there are no tokens left it gives the reset time.
    license: MIT
    formats:
      - deb
    bindir: /usr/local/bin

homebrew_casks:
  - name: github-token-limit
    ids:
      - github-token-limit
    repository:
      owner: clivewalkden
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/clivewalkden/homebrew-taps
    description: This executable returns the number of requests remaining for the GitHub API. If there are no tokens left it gives the reset time.
    commit_author:
      name: Clive Walkden
      email: clivewalkden@gmail.com
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-token-limit"]
          end
